site_name: Cloud Architecture notes
site_url: https://dram1964.github.com/cloudarchitect
nav: 
  - 'Home': 'index.md'
  - 'IT Operations':
    - 'SOAR': 'operations/soar.md'
  - 'Azure': 
    - 'AZ104 Reference': 'azure/az104.md'
    - 'CLI Commands': 'azure/cli_commands.md'
    - 'Azure AD': 'azure/aad.md'
    - 'Azure Compute': 'azure/compute.md'
    - 'Azure Key Vault': 'azure/keyvault.md'
    - 'Azure Fundamentals': 
        - 'Core Concepts': 'azure/afc/core_concepts.md'
        - 'Core Services': 'azure/afc/core_services.md'
        - 'Core Management Tools': 'azure/afc/core_management_tools.md'
        - 'Security': 'azure/afc/security.md'
        - 'Governance': 'azure/afc/governance.md'
        - 'Costs': 'azure/afc/costs.md'
    - 'App Service':
        - 'App Service Overview': 'azure/app_service/app_service.md'
        - 'App Service Deplyment: Part 1': 'azure/app_service/flask_app_service_part_one.md'
    - 'KQL': 'azure/kusto.md'
    - 'Azure Monitor' : 'azure/monitor.md'
    - 'Azure Networking': 'azure/networking.md'
    - 'Azure Storage': 'azure/storage.md'
    - 'Databases':
      - 'PostgreSQL': 'azure/db/postgresql.md'
      - 'CosmosDB': 'azure/db/cosmosdb.md'
    - 'Machine Learning': 'azure/aml.md'
  - 'Devops':
    - 'Overview': 'devops/devops.md'
    - 'Git Client': 'devops/git_commands.md'
    - 'Github Actions': 'devops/github_actions.md'
    - 'Porter': 'devops/porter.md'
    - 'Terraform': 
        - 'Intro': 'devops/terraform/intro.md'
        - 'Blocks': 'devops/terraform/blocks.md'
        - 'Variables': 'devops/terraform/variables.md'
        - 'Meta-Arguments': 'devops/terraform/meta.md'
        - 'Functions': 'devops/terraform/functions.md'
        - 'Provisioners': 'devops/terraform/provisioner.md'
        - 'Modules': 'devops/terraform/modules.md'
        - 'Remote State': 'devops/terraform/state.md'
    - 'Cloud Init': 'devops/cloudinit.md'
  - 'Linux':
    - 'Commands': 'linux/commands.md'
    - 'Bash Scripting': 'linux/bash_scripting.md'
    - 'Awk': 'linux/awk.md'
    - 'Performance': 'linux/performance.md'
  - 'Databricks':
    - 'Overview': 'databricks/overview.md'
    - 'Databbricks Lakehouse Fundamentals': 'databricks/fundamentals.md'
  - 'Python': 
    - 'venv': 'python/venv.md'
    - 'Pandas': 'python/pandas.md'
