site_name: Cloud Architecture notes
site_url: https://dram1964.github.com/cloudarchitect
nav: 
  - 'Home': 'index.md'
  - 'Azure': 
    - 'CLI Commands': 'azure/cli_commands.md'
    - 'Azure AD': 'azure/aad.md'
    - 'Azure Fundamentals': 'azure/afc.md'
    - 'App Service':
        - 'App Service Overview': 'azure/app_service/app_service.md'
        - 'App Service Deplyment: Part 1': 'azure/app_service/flask_app_service_part_one.md'
    - 'KQL': 'azure/kusto.md'
    - 'PostgreSQL': 'azure/postgresql.md'
    - 'Terraform': 'azure/terraform.md'
  - 'Devops': 'devops/devops.md'
  - 'Linux':
    - 'Commands': 'linux/commands.md'
  - 'Git':
    - 'Git Client': 'git/git_commands.md'
    - 'Github Actions': 'git/github_actions.md'
  - 'Porter': 'porter.md'
